services:
  user-service:
    build: ./services/user
    container_name: user-service
    ports:
      - "3011:4001"
    environment:
      NODE_ENV: "production"
      PORT: 4001
      JWT_SECRET: ${JWT_SECRET}
      MONGODB_DATABASE_URL: ${MONGODB_DATABASE_URL}
      MONGODB_DATABASE_NAME: ${MONGODB_DATABASE_NAME}
      DATABASE_URL:
        ${DATABASE_URL}
        #    volumes:
      #      - ./services/user:/chat
  admin-service:
    build: ./services/admin
    container_name: admin-service
    ports:
      - "3012:4002"
    environment:
      NODE_ENV: "production"
      PORT: 4002
      MONGODB_DATABASE_URL: ${MONGODB_DATABASE_URL}
      MONGODB_DATABASE_NAME: ${MONGODB_DATABASE_NAME}
      DATABASE_URL:
        ${DATABASE_URL}
        #   volumes:
      # - ./services/admin:/admin
  chat-service:
    build: ./services/chat
    container_name: chat-service
    ports:
      - "3013:4004"
    environment:
      NODE_ENV: "production"
      PORT: 4004
      MONGODB_DATABASE_URL: ${MONGODB_DATABASE_URL}
      MONGODB_DATABASE_NAME: ${MONGODB_DATABASE_NAME}
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
  daily-service:
    build: ./services/daily
    container_name: daily-service
    ports:
      - "3014:4006"
    environment:
      NODE_ENV: "production"
      PORT: 4006
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MONGODB_DATABASE_URL: ${MONGODB_DATABASE_URL}
      MONGODB_DATABASE_NAME: ${MONGODB_DATABASE_NAME}
      DATABASE_URL: ${DATABASE_URL}
  forum-service:
    build: ./services/forum
    container_name: forum-service
    ports:
      - "3015:4003"
    environment:
      NODE_ENV: "production"
      PORT: 4003
      MONGODB_DATABASE_URL: ${MONGODB_DATABASE_URL}
      MONGODB_DATABASE_NAME: ${MONGODB_DATABASE_NAME}
      DATABASE_URL: ${DATABASE_URL}
  schedule-service:
    build: ./services/schedule
    container_name: schedule-service
    ports:
      - "3016:4005"
    environment:
      NODE_ENV: "production"
      PORT: 4005
      MONGODB_DATABASE_URL: ${MONGODB_DATABASE_URL}
      MONGODB_DATABASE_NAME: ${MONGODB_DATABASE_NAME}
      DATABASE_URL: ${DATABASE_URL}

  orchestrator:
    build: ./orchestrator
    container_name: orchestrator
    ports:
      - "3017:4000"
        #volumes:
      #- ./services/user:/chat
    environment:
      NODE_ENV: "production"
      PORT: 4000
      REDIS_URL: ${REDIS_URL}
      CALLBACK_TOKEN: ${CALLBACK_TOKEN}
      USER_URL: "http://user-service:4001"
      ADMIN_URL: "http://admin-service:4002"
      FORUM_URL: "http://forum-service:4003"
      CHAT_URL: "http://chat-service:4004"
      SCHEDULE_URL: "http://schedule-service:4005"
      DAILY_URL: "http://daily-service:4006"

  pg_livy:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
  mongo_livy:
    image: mongo:6
  redis_livy:
    image: redis:7.0.11
